platform :ios, '7.0'
inhibit_all_warnings!

pod 'Mantle'
pod 'LBBlurredImage'
pod 'TSMessages'
pod 'ReactiveCocoa'
pod 'HexColors'
pod 'GVUserDefaults'
pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'BlocksKit'
pod 'NZAlertView'
pod 'MBProgressHUD'
pod 'SIAlertView'
pod 'BZGFormField'
pod 'UzysCircularProgressPullToRefresh'
pod 'AFNetworking'
pod 'FastAnimationWithPOP'


